name: "Update the changelog"
description: "Updates the changelog based on changes through start tag and HEAD"
inputs:
  changelog-template-file:
    description: "Template file for the changelog"
    required: false
  changelog-file:
    description: "Changelog file to update"
    required: true
  changelog-start-tag:
    description: "A tag from which changelog starts generating the history"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.changelog-file }}
    - ${{ inputs.changelog-start-tag }}
    - ${{ inputs.changelog-template-file }}
